name: Solution Submission
description: Submit your OutStem coding challenge solution
title: '[Submission]: YOUR_NAME coding challenge submission'
assignees:
  - ebivibe
body:
  - type: markdown
    attributes:
      value: |
        Thank you for completing the OutStem Coding Challenge! 🎉🎉

        Please submit your solution using this form.
  - type: input
    id: contact
    attributes:
      label: Your Name
      placeholder: Youssef Jallouli
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Your Email
      placeholder: yjall032@uottawa.ca
    validations:
      required: true
  - type: input
    id: source-url
    attributes:
      label: Source Code URL
      description: My repo is in this Fork.
    validations:
      required: true
  - type: input
    id: hosted-url
    attributes:
      label: Hosted URL
      description: This is the URL for your hosted project.
  - type: textarea
    id: run-instructions
    attributes:
      label: Run instructions
      description: Explain how to properly run your app.
      placeholder: |
        1-To run an application in Angular, you will need to have Node.js and the Angular CLI (Command Line Interface) installed on your computer.
        2-Open a terminal window and navigate to the directory where you want to clone this application. 
        3-Run the following command to install the Angular CLI globally: npm install -g @angular/cli
        4-Navigate into the new application directory.
        5-You can now run the development server by using the command : ng serve, 
        6-This will start the development server and open the application in a web browser at http://localhost:4200/
        7- This will create a production-ready build of your application in the dist folder by using the command :ng build --prod 
        
  - type: textarea
    id: goals-completed
    attributes:
      label: Goals Completed
      description: Which goals did you complete?
      placeholder: |
        Ex. I completed goals 1 to 6.
  - type: textarea
    id: anything-else
    attributes:
      label: not tested enough.
